name: Build/release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Get the ffmpeg binaries
        if: startsWith(matrix.os, 'ubuntu') || startsWith(matrix.os, 'macos')
        run: |
          curl -L https://rebaslight.s3.amazonaws.com/build/ffmpeg-bins-4.4.1.tar.xz -o ffmpeg-bins.tar.xz
          tar xf ffmpeg-bins.tar.xz

      - name: Get the ffmpeg binaries
        if: startsWith(matrix.os, 'windows')
        run: |
          curl -L https://rebaslight.s3.amazonaws.com/build/ffmpeg-bins-4.4.1-win.zip -o ffmpeg-bins.zip
          unzip ffmpeg-bins.zip

      - name: Build/release Electron app
        uses: samuelmeuli/action-electron-builder@v1
        with:
          build_script_name: bundle-p
          # GitHub token, automatically provided to the action
          # (No need to define this secret in the repo settings)
          github_token: ${{ secrets.github_token }}

          # If the commit is tagged with a version (e.g. "v1.0.0"),
          # release the app after building
          release: ${{ startsWith(github.ref, 'refs/tags/v') }}

          # Windows
          windows_certs: ${{ secrets.windows_certs }}
          windows_certs_password: ${{ secrets.windows_certs_password }}
